name: build & push

on:
  push:
    branches: [master, cal]
jobs:
  build_push_to_ecr:
    runs-on: self-hosted
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.3.3
      with:
        ref: cal
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: us-west-2
        
    - name: ecr login
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: build & push rest
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: rest-api-server
      run: |
        dt=$(date +%d%m%y)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$dt -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f  Dockerfile_py3 .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$dt && docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest 
        
    - name: build & push psap
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: psap
      run: |
        dt=$(date +%d%m%y)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$dt -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f  Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$dt && docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
    - name: deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: psap
        IMAGE_TAG: latest
      with:
        args: set image deployment/$ECR_REPOSITORY $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --record
  
    - name: verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: rollout status deployment/admin-ui
        
